#!/usr/bin/env python3
"""Patch gateway+WebUI: durable run-scoped YOLO + deny-reason relay.

Problem (issue #136 / WebUI approval hardening):
  1. In gateway mode (webui_chat_backend=gateway) the AGENT and its approval
     state (tools.approval._session_yolo) run in the GATEWAY process. The
     WebUI's /api/session/yolo POST calls enable_session_yolo() on the WEBUI
     process's own copy, which never reaches the gateway — so the YOLO toggle
     appeared to work (frontend re-fetched its own flag) but never actually
     auto-approved anything at the enforcement boundary.
  2. The approval enforcement key in the gateway is the RUN ID
     (approval_session_key = run_id, set_current_session_key(run_id)), NOT
     the WebUI sid.  YOLO keyed by sid never reaches the enforcement boundary
     either — the toggle must be applied to the run's approval key.
  3. YOLO was in-memory only: a server/gateway restart silently dropped every
     session's auto-approve mode.
  4. A deny from the approval card/banner never carried a reason.

Fix (four files; same fail-loud / idempotent rules as patch-approval.py):
  1. api_server.py (gateway):
       * POST /v1/yolo {run_id?, session_id?, enabled} -> resolves the target
         run(s) (explicit run_id, or sid -> active run via _run_statuses /
         _run_approval_sessions) and enable_session_yolo(run_id) /
         disable_session_yolo(run_id) in the GATEWAY process — the key the
         approval boundary actually checks.
       * GET  /v1/yolo/{session_id} -> is_session_yolo_enabled() for the
         active run(s) of that sid (authoritative read for the WebUI).
       * _handle_run_approval: relay body.reason into
         resolve_gateway_approval(..., reason=...) so an explicit deny shows
         the user's reason to the agent.
  2. runner_client.py (webui): HttpRunnerClient.set_run_yolo(),
     get_run_yolo(), and respond_approval(..., reason=None).
  3. routes.py (webui): /api/session/yolo POST persists to a durable store
     (STATE_DIR/approval_mode.json, atomic) AND relays to the gateway
     endpoint for immediate enforcement; GET reads gateway-backed state. Plus
     reapply_persisted_yolo() so yolo re-applies on boot / gateway reconnect.
  4. server.py (webui): call reapply_persisted_yolo() once at boot so a
     restart re-applies any persisted run yolo to the gateway.

Rules (patch-approval.py pattern):
  - Fail LOUDLY (exit 1) when an anchor is absent or appears more than once
    (upgrade drift -> caught at build time, not silently skipped).
  - Idempotent: safe to run repeatedly on an already-patched file.

Usage:
  python3 patch-approval-yolo-durable.py \\
      /app/hermes-agent/gateway/platforms/api_server.py \\
      /app/hermes-webui/api/runner_client.py \\
      /app/hermes-webui/api/routes.py \\
      /app/hermes-webui/server.py
"""

import sys

MARK_API = "yolo-durable; gateway /v1/yolo + deny-reason relay"
MARK_RUNNER = "yolo-durable; set/get_run_yolo + respond_approval reason"
MARK_ROUTES = "yolo-durable; durable store + gateway relay + reapply"
MARK_SERVER = "yolo-durable; boot-time reapply of persisted yolo"

# ---------------------------------------------------------------------------
# api_server.py (gateway process) patches
# ---------------------------------------------------------------------------

API_PATCHES = [
    # 0. Module-level safe-id helper for the /v1/yolo handlers.
    {
        "anchor": "def _coerce_request_bool(value: Any, default: bool = False) -> bool:",
        "old": "def _coerce_request_bool(value: Any, default: bool = False) -> bool:",
        "new": (
            "def _is_safe_yolo_id(value: str) -> bool:\n"
            '    """Return True when ``value`` is a safe yolo target id.\n'
            "\n"
            "    Session/runtime ids are WebUI conversation ids and gateway run\n"
            "    ids (run_<hex>).  Both are generated by the platform and carry\n"
            "    only [A-Za-z0-9_-].  Reject anything else so a crafted id cannot\n"
            "    smuggle path/query metacharacters into the /v1/yolo handlers or\n"
            "    the durable store keys (approval-hardening #136).\n"
            '    """\n'
            "    if not value:\n"
            "        return False\n"
            "    import re as _re\n"
            "\n"
            "    return bool(_re.fullmatch(r\"[A-Za-z0-9][A-Za-z0-9_-]{0,127}\", value))\n"
            "\n"
            "\n"
            "def _coerce_request_bool(value: Any, default: bool = False) -> bool:"
        ),
        "description": "module-level _is_safe_yolo_id helper",
    },
    # 1. Module docstring — document the new /v1/yolo endpoints.
    {
        "anchor": "- POST /v1/yolo",
        "old": "- GET  /v1/runs/{run_id}/approval — read the pending approval for a run",
        "new": (
            "- GET  /v1/runs/{run_id}/approval — read the pending approval for a run\n"
            "- POST /v1/yolo                  — set/clear run-scoped YOLO bypass\n"
            "- GET  /v1/yolo/{session_id}     — read YOLO state for a session\n"
            "\n"
            + MARK_API
        ),
        "description": "api_server docstring notes",
    },
    # 2. Register routes alongside the runs approval routes.
    {
        "anchor": "self._app.router.add_get(\"/v1/runs/{run_id}/approval\", self._handle_get_run_approval)",
        "old": 'self._app.router.add_get("/v1/runs/{run_id}/approval", self._handle_get_run_approval)',
        "new": (
            'self._app.router.add_get("/v1/runs/{run_id}/approval", self._handle_get_run_approval)\n'
            '            self._app.router.add_post("/v1/yolo", self._handle_yolo_set)\n'
            '            self._app.router.add_get("/v1/yolo/{session_id}", self._handle_yolo_get)'
        ),
        "description": "route registration for /v1/yolo",
    },
    # 2b. __init__: per-session YOLO override map (cross-message durability).
    {
        "anchor": "self._run_approval_sessions: Dict[str, str] = {}",
        "old": "self._run_approval_sessions: Dict[str, str] = {}",
        "new": (
            "self._run_approval_sessions: Dict[str, str] = {}\n"
            "\n"
            "        # Per-session durable YOLO override (cross-message persistence).\n"
            "        # Keyed by WebUI sid -> bool.  Unlike _session_yolo in\n"
            "        # tools.approval (keyed by the run's approval key = run_id,\n"
            "        # which is FRESH per message), this map survives individual\n"
            "        # runs: the run-start binding in _handle_runs reads it and\n"
            "        # calls enable_session_yolo(run_id) so EVERY new run in the\n"
            "        # session auto-approves.  Populated by _handle_yolo_set and\n"
            "        # re-seeded from the WebUI durable store on reconnect.\n"
            "        self._session_yolo_override: Dict[str, bool] = {}"
        ),
        "description": "init per-session yolo override map",
    },
    # 2c. run-start binding: seed every new run with the session's override.
    {
        "anchor": "self._run_approval_sessions[run_id] = approval_session_key",
        "old": "self._run_approval_sessions[run_id] = approval_session_key",
        "new": (
            "self._run_approval_sessions[run_id] = approval_session_key\n"
            "        # vulpy-override-seed: carry the session's YOLO override to this new\n"
            "        # run.  The enforcement boundary is keyed by the run's\n"
            "        # approval key (run_id), and run_id is FRESH per message, so a\n"
            "        # toggle applied only at set-time dies with the run.  Reading\n"
            "        # self._session_yolo_override[session_id] here and calling\n"
            "        # enable_session_yolo(run_id) is what makes YOLO persist across\n"
            "        # messages (run N+1 in the session is auto-approved too).\n"
            "        if self._session_yolo_override.get(session_id):\n"
            "            try:\n"
            "                from tools.approval import enable_session_yolo\n"
            "\n"
            "                enable_session_yolo(run_id)\n"
            "            except Exception:\n"
            "                logger.exception(\"[api_server] yolo run-seed failed for %s\", run_id)\n"
        ),
        "description": "seed new runs with the session yolo override",
    },
    {
        "anchor": '    async def _handle_stop_run(self, request: "web.Request") -> "web.Response":',
        "old": '    async def _handle_stop_run(self, request: "web.Request") -> "web.Response":',
        "new": (
            '    async def _handle_yolo_set(self, request: "web.Request") -> "web.Response":\n'
            '        """POST /v1/yolo — set or clear YOLO bypass for a run and/or a session.\n'
            "\n"
            "        The approval boundary in this process (tools.approval) is keyed\n"
            "        by the RUN'S approval session key (run_id, see _handle_runs),\n"
            "        NOT the WebUI sid — and each run gets a FRESH run_id.  So a\n"
            "        toggle that only applies to the current run is lost on the next\n"
            "        message.  This handler therefore keeps a DURABLE per-session\n"
            "        override (self._session_yolo_override[sid]) that the run-start\n"
            "        binding reads to auto-approve EVERY new run in the session\n"
            "        (cross-message persistence).\n"
            "\n"
            "        Body:\n"
            "          run_id?      apply to this specific run.\n"
            "          session_id?  the WebUI conversation sid to override.\n"
            "          enabled      bool.\n"
            "        A session_id (with or without run_id) records the override\n"
            "        (future runs) AND applies to the sid's active run(s). A bare\n"
            "        run_id applies to the run and resolves the sid for the override.\n"
            "        With no active run for a sid, writing the override still\n"
            "        succeeds so a fresh session / post-restart reapply works.\n"
            '        """\n'
            "        auth_err = self._check_auth(request)\n"
            "        if auth_err:\n"
            "            return auth_err\n"
            "        try:\n"
            "            body = await request.json()\n"
            "        except Exception:\n"
            '            return web.json_response(_openai_error("Invalid JSON"), status=400)\n'
            '        run_id = str(body.get("run_id") or "").strip()\n'
            '        session_id = str(body.get("session_id") or "").strip()\n'
            "        if not run_id and not session_id:\n"
            "            return web.json_response(\n"
            '                _openai_error("Missing run_id or session_id", code="missing_target"),\n'
            "                status=400,\n"
            "            )\n"
            '        # Session/run id validation (approval-hardening #136): only\n'
            '        # accept ids that cannot smuggle path/query metacharacters.\n'
            '        if not _is_safe_yolo_id(session_id) or not _is_safe_yolo_id(run_id):\n'
            "            return web.json_response(\n"
            '                _openai_error("Invalid session_id or run_id", code="invalid_target"),\n'
            "                status=400,\n"
            "            )\n"
            '        enabled = _coerce_request_bool(body.get("enabled"), default=True)\n'
            "        from tools.approval import enable_session_yolo, disable_session_yolo\n"
            "\n"
            "        # 1) Record the per-session override (cross-message durability).\n"
            "        # Resolve the sid: explicit session_id, else the run's reported\n"
            "        # session id from _run_statuses.\n"
            "        override_sid = session_id\n"
            "        if not override_sid and run_id:\n"
            "            override_sid = str((self._run_statuses.get(run_id) or {}).get(\"session_id\") or \"\")\n"
            "        if override_sid:\n"
            "            if enabled:\n"
            "                self._session_yolo_override[override_sid] = True\n"
            "            else:\n"
            "                self._session_yolo_override.pop(override_sid, None)\n"
            "\n"
            "        # 2) Apply to the targeted run(s).\n"
            "        targets = []\n"
            "        if run_id:\n"
            "            targets.append(run_id)\n"
            "        if session_id:\n"
            "            # session_id -> active run(s).  A sid can legitimately map\n"
            "            # to multiple concurrent runs (delegated children share the\n"
            "            # parent sid); apply to ALL so the flag never misses the\n"
            "            # run that is about to ask for approval.\n"
            "            for rid, key in list(self._run_approval_sessions.items()):\n"
            "                status = self._run_statuses.get(rid, {})\n"
            "                if status.get(\"status\") in (\"completed\", \"failed\", \"cancelled\"):\n"
            "                    continue\n"
            "                if str(status.get(\"session_id\") or \"\") == session_id:\n"
            "                    targets.append(rid)\n"
            "        if not targets and not override_sid:\n"
            "            # Nothing to apply and no durable override to record.\n"
            "            return web.json_response(\n"
            "                _openai_error(\n"
            "                    \"No active run and no session to persist\",\n"
            "                    code=\"run_not_found\",\n"
            "                ),\n"
            "                status=404,\n"
            "            )\n"
            "        try:\n"
            "            for rid in targets:\n"
            "                if enabled:\n"
            "                    enable_session_yolo(rid)\n"
            "                else:\n"
            "                    disable_session_yolo(rid)\n"
            "        except Exception as exc:\n"
            "            logger.exception(\"[api_server] yolo-set failed for %s\", targets)\n"
            '            return _openai_error(str(exc))\n'
            '        return web.json_response({"ok": True, "run_ids": targets, "yolo_enabled": enabled})\n'
            "\n"
            '    async def _handle_yolo_get(self, request: "web.Request") -> "web.Response":\n'
            '        """GET /v1/yolo/{session_id} — read a session\'s YOLO state.\n'
            "\n"
            "        Returns True when ANY active run mapped to the sid has yolo\n"
            "        enabled (the flag is enforced per-run).\n"
            '        """\n'
            "        auth_err = self._check_auth(request)\n"
            "        if auth_err:\n"
            "            return auth_err\n"
            '        session_id = (request.match_info.get("session_id") or "").strip()\n'
            "        if not session_id:\n"
            "            return web.json_response(\n"
            '                _openai_error("Missing session_id", code="missing_session_id"),\n'
            "                status=400,\n"
            "            )\n"
            '        if not _is_safe_yolo_id(session_id):\n'
            "            return web.json_response(\n"
            '                _openai_error("Invalid session_id", code="invalid_session_id"),\n'
            "                status=400,\n"
            "            )\n"
            "        try:\n"
            "            from tools.approval import is_session_yolo_enabled\n"
            "            enabled = bool(self._session_yolo_override.get(session_id))\n"
            "            for rid, key in list(self._run_approval_sessions.items()):\n"
            "                status = self._run_statuses.get(rid, {})\n"
            "                if str(status.get(\"session_id\") or \"\") != session_id:\n"
            "                    continue\n"
            "                if is_session_yolo_enabled(rid):\n"
            "                    enabled = True\n"
            "                    break\n"
            "        except Exception as exc:\n"
            "            logger.exception(\"[api_server] yolo-get failed for %s\", session_id)\n"
            '            return web.json_response(_openai_error(str(exc)), status=500)\n'
            '        return web.json_response({"yolo_enabled": enabled, "session_id": session_id})\n'
            "\n"
            '    async def _handle_stop_run(self, request: "web.Request") -> "web.Response":'
        ),
        "description": "add _handle_yolo_set + _handle_yolo_get handlers",
    },
    # 4. _handle_run_approval: relay body.reason to resolve_gateway_approval.
    {
        "anchor": (
            "            resolved = resolve_gateway_approval(\n"
            "                approval_session_key,\n"
            "                choice,\n"
            "                resolve_all=resolve_all,\n"
            "            )"
        ),
        "old": (
            "            resolved = resolve_gateway_approval(\n"
            "                approval_session_key,\n"
            "                choice,\n"
            "                resolve_all=resolve_all,\n"
            "            )"
        ),
        "new": (
            "            # Deny-reason hardening: the reason is relayed into the\n"
            "            # agent's context as quoted data (BLOCKED message), so cap it\n"
            "            # at 500 chars and strip control chars/newlines — it must stay\n"
            "            # a single bounded quoted line, never unbounded/prompt-injectable\n"
            "            # text. (Gateway-side bound; the WebUI also sanitizes before POST.)\n"
            "            deny_reason = str(body.get('reason') or '').strip()\n"
            "            if deny_reason:\n"
            "                deny_reason = ' '.join(deny_reason.split())[:500]\n"
            "            resolved = resolve_gateway_approval(\n"
            "                approval_session_key,\n"
            "                choice,\n"
            "                resolve_all=resolve_all,\n"
            "                reason=deny_reason or None,\n"
            "            )"
        ),
        "description": "_handle_run_approval: thread body.reason into resolve_gateway_approval",
    },
]

# ---------------------------------------------------------------------------
# runner_client.py patches
# ---------------------------------------------------------------------------

RUNNER_PATCHES = [
    {
        "anchor": (
            "    def respond_approval(self, run_id: str, approval_id: str, choice: str) -> dict[str, Any]:\n"
            "        return self._post(\n"
            '            f"/v1/runs/{urllib.parse.quote(str(run_id), safe=\'\')}/approval",\n'
            '            {"choice": choice, "approval_id": approval_id},\n'
            "        )"
        ),
        "old": (
            "    def respond_approval(self, run_id: str, approval_id: str, choice: str) -> dict[str, Any]:\n"
            "        return self._post(\n"
            '            f"/v1/runs/{urllib.parse.quote(str(run_id), safe=\'\')}/approval",\n'
            '            {"choice": choice, "approval_id": approval_id},\n'
            "        )"
        ),
        "new": (
                    "    def respond_approval(self, run_id: str, approval_id: str, choice: str, reason: str | None = None) -> dict[str, Any]:\n"
                    "        payload: dict[str, Any] = {\"choice\": choice, \"approval_id\": approval_id}\n"
                    "        if choice == \"deny\" and reason:\n"
                    "            # Deny-reason hardening: cap at 500 chars + strip control\n"
                    "            # chars/newlines so the reason is a single bounded quoted\n"
                    "            # line in the agent's context (defense-in-depth; WebUI and\n"
                    "            # gateway relay also bound it).\n"
                    "            _reason = ' '.join(str(reason).split())[:500]\n"
                    "            if _reason:\n"
                    "                payload[\"reason\"] = _reason\n"
                    "        return self._post(\n"
                    '            f"/v1/runs/{urllib.parse.quote(str(run_id), safe=\'\')}/approval",\n'
                    "            payload,\n"
                    "        )\n"
                    "\n"
                    "    def set_run_yolo(self, run_id: str, enabled: bool) -> dict[str, Any]:\n"
                    "        \"\"\"POST /v1/yolo — set/clear run-scoped YOLO in the gateway process.\n"
                    "\n"
                    "        The gateway resolves the run's approval session key (the\n"
                    "        enforcement boundary is keyed by run_id), so the WebUI sends\n"
                    "        the run_id it discovered for this session.\n"
                    "        \"\"\"\n"
                    "        return self._post(\n"
                    '            "/v1/yolo",\n'
                    '            {"run_id": run_id, "enabled": bool(enabled)},\n'
                    "        )\n"
                    "\n"
                    "    def set_session_yolo_override(self, session_id: str, enabled: bool) -> dict[str, Any]:\n"
                    "        \"\"\"Record (or clear) a session's durable YOLO override in the gateway.\n"
                    "\n"
                    "        The gateway keeps the override keyed by the WebUI sid and\n"
                    "        seeds every new run_id in that session from it (cross-message\n"
                    "        persistence).  Works even when the session has no active run,\n"
                    "        so a fresh session / post-restart reapply carries the flag.\n"
                    "        \"\"\"\n"
                    "        return self._post(\n"
                    '            "/v1/yolo",\n'
                    '            {"session_id": session_id, "enabled": bool(enabled)},\n'
                    "        )\n"
                    "\n"
                    "    def get_run_yolo(self, session_id: str) -> dict[str, Any]:\n"
                    "        \"\"\"Read a session's YOLO state from the gateway (per active run).\n"
                    "\n"
                    "        Returns the gateway's {yolo_enabled, session_id} dict (already\n"
                    "        JSON); callers read result['yolo_enabled'] when the call succeeds.\n"
                    "        \"\"\"\n"
                    "        return self._get(\n"
                    '            f"/v1/yolo/{urllib.parse.quote(str(session_id), safe=\'\')}"\n'
                    "        )\n"
                    "\n"
                    "    # yolo-durable; set/get_run_yolo + respond_approval reason\n"
                ),
        "description": "respond_approval reason + set/get_run_yolo on the runner client",
    },
]
# ---------------------------------------------------------------------------
# routes.py patches: durable store + gateway relay + reapply
# ---------------------------------------------------------------------------

# The durable store helpers + reapply are inserted once before
# _handle_approval_pending. The POST /api/session/yolo handler is extended to
# relay to the gateway + persist. The GET handler is patched to read the
# gateway-backed state. The respond handler threads body.reason.

ROUTES_PRE_HOOK = "def _handle_approval_pending(handler, parsed):"

ROUTES_STORE_HELPERS = """#{marker}
def _gateway_yolo_store_path():
    from api.config import STATE_DIR
    import os
    return os.path.join(str(STATE_DIR), "approval_mode.json")


def _load_gateway_yolo_store():
    import json as _json
    import os as _os
    path = _gateway_yolo_store_path()
    try:
        if not _os.path.exists(path):
            return {"version": 2, "sessions": {}}
        with open(path, "r", encoding="utf-8") as f:
            data = _json.load(f)
        if not isinstance(data, dict):
            return {"version": 2, "sessions": {}}
        # Normalize v1 flat {sid: bool} -> v2 {"version":2,"sessions":{sid:{...}}}.
        if data.get("version") == 2:
            sessions = data.get("sessions") or {}
            if not isinstance(sessions, dict):
                sessions = {}
            return {
                "version": 2,
                "sessions": {
                    k: {
                        "enabled": bool((v or {}).get("enabled", False)),
                        "pending_confirm": bool((v or {}).get("pending_confirm", False)),
                    }
                    for k, v in sessions.items()
                    if isinstance(v, dict)
                },
            }
        # v1 flat map — every legacy enabled sid becomes enabled with
        # pending_confirm=True so a restart does NOT silently re-arm YOLO
        # without a fresh user confirmation (approval-hardening #136).
        sessions = {}
        for k, v in data.items():
            if not isinstance(v, bool):
                continue
            sessions[k] = {
                "enabled": v,
                "pending_confirm": v,  # must re-confirm after schema bump
            }
        return {"version": 2, "sessions": sessions}
    except Exception:
        return {"version": 2, "sessions": {}}


def _save_gateway_yolo_store(payload: dict) -> None:
    import json as _json
    import os as _os
    import tempfile as _tempfile
    path = _gateway_yolo_store_path()
    try:
        _os.makedirs(_os.path.dirname(path), exist_ok=True)
        # Security hardening (approval-hardening #136): write via os.open with
        # O_NOFOLLOW + mode 0o600 so an attacker (or a stray symlink) cannot
        # redirect the durable store through a symlink to an arbitrary file.
        # tempfile + os.replace keeps the write atomic; the explicit stat check
        # rejects a symlink at the final path before the replace lands.
        if _os.path.islink(path):
            _os.remove(path)
        fd, tmp = _tempfile.mkstemp(prefix=".approval_mode.", dir=_os.path.dirname(path))
        try:
            _os.chmod(tmp, 0o600)
            with _os.fdopen(fd, "w", encoding="utf-8") as f:
                _json.dump(payload, f, ensure_ascii=False, indent=2)
                f.flush()
                _os.fsync(f.fileno())
            _os.replace(tmp, path)
        except Exception:
            try:
                _os.unlink(tmp)
            except OSError:
                pass
            raise
    except Exception:
        pass


# YOLO is enforced in the GATEWAY keyed by run_id (approval_session_key).
# The WebUI sid is a conversation scope; the gateway maps sid -> active
# run_id(s).  We persist by sid (the label the user toggled) and relay to
# the gateway by run id so enforcement actually happens.

def _resolve_gateway_run_id(sid: str) -> str:
    \"\"\"Resolve a session id to its active gateway run id (or \"\").

    Mirrors the discovery in _handle_approval_pending: the gateway's
    GET /api/sessions/{sid}/active-run returns {run_id, status} for the
    newest active run (queued/running/waiting_for_approval).
    \"\"\"
    try:
        from api.gateway_chat import (
            webui_gateway_chat_enabled,
            _gateway_base_url,
            _gateway_api_key,
        )
        from api.config import get_config as _gc
        from api.runner_client import HttpRunnerClient, RunnerClientError
        if webui_gateway_chat_enabled(_gc()):
            _cl = HttpRunnerClient(
                base_url=_gateway_base_url(_gc()),
                api_key=_gateway_api_key(),
            )
            _active = _cl.get_active_run(sid)
            return str((_active or {}).get(\"run_id\") or \"\")
    except Exception:
        pass
    return \"\"


def reapply_persisted_yolo() -> int:
    \"\"\"Audit persisted session YOLO at boot; do NOT silently re-arm.

    Call once at WebUI startup (and after any gateway reconnect).  Iterates
    the durable approval_mode.json.  A session whose gateway override is
    still live keeps working (no confirmation needed — nothing was lost).
    A session whose override is gone (gateway/agent restart dropped the
    in-memory map) is marked ``pending_confirm`` and is NOT re-armed: YOLO
    only comes back after the user re-confirms in that session
    (approval-hardening #136 — re-confirm-once across restart).

    Returns the number of sessions audited (enabled pending or live).
    \"\"\"
    store = _load_gateway_yolo_store()
    sessions = store.get(\"sessions\") or {}
    enabled = [sid for sid, rec in sessions.items() if rec.get(\"enabled\")]
    if not enabled:
        return 0
    audited = 0
    dirty = False
    try:
        from api.gateway_chat import (
            webui_gateway_chat_enabled,
            _gateway_base_url,
            _gateway_api_key,
        )
        from api.config import get_config as _gc
        from api.runner_client import HttpRunnerClient, RunnerClientError
        if webui_gateway_chat_enabled(_gc()):
            _cfg = _gc()
            _cl = HttpRunnerClient(
                base_url=_gateway_base_url(_cfg),
                api_key=_gateway_api_key(),
            )
            for sid in enabled:
                # Never re-assert yolo for voiced subagent child sessions:
                # their shared approval boundary is owned by the parent sid.
                if _is_subagent_child_session_id(sid):
                    continue
                try:
                    _live_res = _cl.get_run_yolo(sid) or {}
                    live = bool(_live_res.get("yolo_enabled"))
                    rec = sessions.setdefault(
                        sid, {"enabled": True, "pending_confirm": False}
                    )
                    if live:
                        # Gateway still enforces — nothing was lost.
                        rec[\"pending_confirm\"] = False
                    else:
                        # Override vanished (restart). Do NOT re-arm silently;
                        # require a one-time user confirmation.
                        rec[\"pending_confirm\"] = True
                    dirty = True
                    audited += 1
                except (RunnerClientError, ValueError):
                    continue
    except Exception:
        pass
    if dirty:
        _save_gateway_yolo_store(store)
    return audited


_runtime_gateway_yolo_cache = {}


def _is_gateway_yolo_enabled(sid: str) -> bool:
    \"\"\"Read a session's YOLO flag (gateway-backed, then the durable store).\"\"\"
    if sid in _runtime_gateway_yolo_cache:
        return _runtime_gateway_yolo_cache[sid]
    flag = False
    try:
        from api.gateway_chat import (
            webui_gateway_chat_enabled,
            _gateway_base_url,
            _gateway_api_key,
        )
        from api.config import get_config as _gc
        from api.runner_client import HttpRunnerClient, RunnerClientError
        if webui_gateway_chat_enabled(_gc()):
            _cfg = _gc()
            _cl = HttpRunnerClient(
                base_url=_gateway_base_url(_cfg),
                api_key=_gateway_api_key(),
            )
            res = _cl.get_run_yolo(sid)
            flag = bool(res and res.get(\"yolo_enabled\"))
    except Exception:
        flag = False
    store = _load_gateway_yolo_store()
    rec = (store.get(\"sessions\") or {}).get(sid) or {}
    flag = flag or bool(rec.get(\"enabled\"))
    _runtime_gateway_yolo_cache[sid] = flag
    return flag


def _gateway_yolo_pending_confirm(sid: str) -> bool:
    \"\"\"True when the session's persisted YOLO needs a fresh confirmation.\"\"\"
    store = _load_gateway_yolo_store()
    rec = (store.get(\"sessions\") or {}).get(sid) or {}
    return bool(rec.get(\"pending_confirm\")) and bool(rec.get(\"enabled\"))


def set_gateway_yolo_enabled(sid: str, enabled: bool) -> None:
    \"\"\"Persist a session's YOLO flag to the durable store + runtime cache.\"\"\"
    store = _load_gateway_yolo_store()
    sessions = store.setdefault(\"sessions\", {})
    if enabled:
        prev = sessions.get(sid) or {}
        sessions[sid] = {
            \"enabled\": True,
            # A user toggle is itself the confirmation.
            \"pending_confirm\": False,
            \"confirmed_at\": prev.get(\"confirmed_at\"),
        }
    else:
        sessions.pop(sid, None)
    _save_gateway_yolo_store(store)
    _runtime_gateway_yolo_cache[sid] = bool(enabled)


def _handle_approval_pending(handler, parsed):"""

# GET /api/session/yolo — replace the local read with the gateway-backed read.
ROUTES_GET_OLD = """    if parsed.path == "/api/session/yolo":
        sid = parse_qs(parsed.query).get("session_id", [""])[0]
        if not sid:
            return bad(handler, "Missing session_id")
        return j(handler, {"yolo_enabled": is_session_yolo_enabled(sid)})"""

ROUTES_GET_NEW = """    if parsed.path == "/api/session/yolo":
        sid = parse_qs(parsed.query).get("session_id", [""])[0]
        if not sid:
            return bad(handler, "Missing session_id")
        # yolo-durable: read gateway-backed state (agent boundary) so the flag
        # reflects actual enforcement, not the WebUI process's own copy.
        # pending_confirm tells the UI a restart dropped the live override and
        # the user must re-confirm before YOLO re-arms (approval-hardening #136).
        try:
            from api.routes import _gateway_yolo_pending_confirm
            _pending = _gateway_yolo_pending_confirm(sid)
        except Exception:
            _pending = False
        return j(handler, {
            "yolo_enabled": _is_gateway_yolo_enabled(sid),
            "pending_confirm": _pending,
        })"""

# POST /api/session/yolo — relay to gateway + persist. Reuse the existing
# stubs but insert the relay + persist before the enable/disable branches.
YOLO_POST_OLD = """        sid = body["session_id"]
        enabled = bool(body.get("enabled", True))
        if enabled:"""

YOLO_POST_NEW = """        sid = body["session_id"]
        enabled = bool(body.get("enabled", True))
        # ---- yolo-durable: relay to gateway + durable persist --------------
        # The gateway enforces yolo keyed by run_id (approval_session_key),
        # so the relay resolves the CURRENT active run for this sid and
        # applies the flag to that run's approval key. Persist keyed by sid
        # (the label the user toggled); reapply_persisted_yolo() re-asserts
        # on boot / gateway reconnect.
        # Delegated subagent children are view-only in the WebUI; a YOLO
        # toggle on the PARENT sid must not drag the child's shared
        # approval boundary into auto-approve (approval-hardening #136).
        if _is_subagent_child_session_id(sid):
            return bad(handler, "Cannot toggle YOLO on a delegated subagent session")
        try:
            from api.gateway_chat import (
                webui_gateway_chat_enabled,
                _gateway_base_url,
                _gateway_api_key,
            )
            from api.config import get_config as _get_cfg
            from api.runner_client import HttpRunnerClient, RunnerClientError
            if webui_gateway_chat_enabled(_get_cfg()):
                _cl = HttpRunnerClient(
                    base_url=_gateway_base_url(_get_cfg()),
                    api_key=_gateway_api_key(),
                )
                _run_id = _resolve_gateway_run_id(sid)
                # Record the durable override (cross-message persistence) even
                # when there is no CURRENT active run, then apply to the live
                # run if one exists.
                _cl.set_session_yolo_override(sid, enabled)
                if _run_id:
                    _cl.set_run_yolo(_run_id, enabled)
        except Exception:
            pass  # gateway relay is best-effort; durable store still applies
        try:
            set_gateway_yolo_enabled(sid, enabled)
        except Exception:
            pass
        # ---- end yolo-durable ----------------------------------------------
        if enabled:"""

# _handle_approval_respond — thread body.reason into the gateway relay.
RESPOND_OLD = (
    "                HttpRunnerClient(base_url=_base, api_key=_key).respond_approval(_run_id, approval_id, choice)"
)
RESPOND_NEW = (
    "                deny_reason = str(body.get('reason') or '').strip()\n"
    "                # Deny-reason hardening: cap at 500 chars + strip control\n"
    "                # chars/newlines so the relay stays a single bounded quoted\n"
    "                # line (network + agent-context bound before the gateway).\n"
    "                if deny_reason:\n"
    "                    deny_reason = ' '.join(deny_reason.split())[:500]\n"
    "                HttpRunnerClient(base_url=_base, api_key=_key).respond_approval(_run_id, approval_id, choice, reason=deny_reason or None)"
)


# ---------------------------------------------------------------------------
# server.py (webui boot) patch: reapply persisted yolo on mount
# ---------------------------------------------------------------------------
SERVER_PATCHES = [
    {
        "anchor": "server.py STATE_DIR.mkdir boot block",
        "old": (
            "    STATE_DIR.mkdir(parents=True, exist_ok=True)\n"
            "    SESSION_DIR.mkdir(parents=True, exist_ok=True)"
        ),
        "new": (
            "    STATE_DIR.mkdir(parents=True, exist_ok=True)\n"
            "    SESSION_DIR.mkdir(parents=True, exist_ok=True)\n"
            "\n"
            "    # " + MARK_SERVER + "\n"
            "    try:\n"
            "        from api.routes import reapply_persisted_yolo\n"
            "        reapplied = reapply_persisted_yolo()\n"
            "        if reapplied:\n"
            "            print(f'[approval] re-applied yolo for {reapplied} session(s) at boot', flush=True)\n"
            "    except Exception as e:\n"
            "        print(f'[approval] yolo boot-reapply skipped: {e}', flush=True)"
        ),
        "description": "boot-time reapply of persisted yolo in server.py",
    },
]


def _apply_one(text: str, patch: dict, file_label: str) -> str:
    anchor = patch["anchor"]
    old = patch["old"]
    count = text.count(old)
    if count == 0:
        sys.stderr.write(
            f"ERROR: anchor not found in {file_label}:\n  anchor: {anchor!r}\n"
            f"  Hermes changed shape — update {__file__}\n"
        )
        sys.exit(1)
    if count > 1:
        sys.stderr.write(
            f"ERROR: anchor appears {count}x in {file_label}:\n  {old!r}\n"
            "  Refusing ambiguous patch.\n"
        )
        sys.exit(1)
    return text.replace(old, patch["new"], 1)


def _apply_all(patches, text, label):
    for p in patches:
        text = _apply_one(text, p, label)
    return text


def main() -> None:
    if len(sys.argv) != 5:
        sys.stderr.write(
            "usage: patch-approval-yolo-durable.py API_SERVER RUNNER_CLIENT ROUTES SERVER\n"
        )
        sys.exit(2)
    api_path, client_path, routes_path, server_path = sys.argv[1:5]

    # ---- api_server.py ----
    with open(api_path, "r", encoding="utf-8") as f:
        api = f.read()
    if MARK_API not in api:
        api = _apply_all(API_PATCHES, api, "api_server.py")
        with open(api_path, "w", encoding="utf-8") as f:
            f.write(api)

    # ---- runner_client.py ----
    with open(client_path, "r", encoding="utf-8") as f:
        client = f.read()
    if MARK_RUNNER not in client:
        client = _apply_all(RUNNER_PATCHES, client, "runner_client.py")
        with open(client_path, "w", encoding="utf-8") as f:
            f.write(client)

    # ---- routes.py ----
    with open(routes_path, "r", encoding="utf-8") as f:
        routes = f.read()
    if MARK_ROUTES not in routes:
        helper_block = ROUTES_STORE_HELPERS.replace("{marker}", MARK_ROUTES, 1)
        if ROUTES_PRE_HOOK not in routes:
            sys.stderr.write(
                "ERROR: routes.py anchor for yolo-store helpers not found.\n"
            )
            sys.exit(1)
        routes = routes.replace(ROUTES_PRE_HOOK, helper_block, 1)
        if ROUTES_GET_OLD in routes:
            routes = routes.replace(ROUTES_GET_OLD, ROUTES_GET_NEW, 1)
        else:
            sys.stderr.write("ERROR: /api/session/yolo GET anchor not found (already patched?)\n")
            sys.exit(1)
        if YOLO_POST_OLD in routes:
            routes = routes.replace(YOLO_POST_OLD, YOLO_POST_NEW, 1)
        else:
            sys.stderr.write("ERROR: /api/session/yolo POST anchor not found (already patched?)\n")
            sys.exit(1)
        if RESPOND_OLD in routes:
            routes = routes.replace(RESPOND_OLD, RESPOND_NEW, 1)
        else:
            sys.stderr.write("ERROR: _handle_approval_respond relay anchor not found (already patched?)\n")
            sys.exit(1)
        with open(routes_path, "w", encoding="utf-8") as f:
            f.write(routes)

    # ---- server.py (webui boot) ----
    with open(server_path, "r", encoding="utf-8") as f:
        server = f.read()
    if MARK_SERVER not in server:
        server = _apply_all(SERVER_PATCHES, server, "server.py")
        with open(server_path, "w", encoding="utf-8") as f:
            f.write(server)


if __name__ == "__main__":
    main()