#!/usr/bin/env node

import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { getRegistryIndex, isAllowedEdit } from "../../design/editor.registry.mjs";

const aliasPattern = /^\{([^}]+)\}$/;
const OLD_DESIGN_MD_VERSION_RE = /^---[\s\S]*?version:\s*["']?1\./m;

function kebabCase(value) {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/[^a-zA-Z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .toLowerCase();
}

function flattenTokens(node, prefix = [], result = new Map()) {
  for (const [key, value] of Object.entries(node)) {
    const tokenPath = [...prefix, key];
    if (value && typeof value === "object" && "$value" in value) {
      result.set(tokenPath.join("."), {
        path: tokenPath,
        type: value.$type,
        value: value.$value,
        description: value.$description,
      });
      continue;
    }
    if (value && typeof value === "object") {
      flattenTokens(value, tokenPath, result);
    }
  }
  return result;
}

function deepMerge(target, source) {
  const output = { ...target };
  for (const [key, value] of Object.entries(source)) {
    const current = output[key];
    const isBranch = value && typeof value === "object" && !Array.isArray(value) && !("$value" in value);
    output[key] = isBranch && current && typeof current === "object" && !Array.isArray(current)
      ? deepMerge(current, value)
      : value;
  }
  return output;
}

function formatValue(value) {
  if (Array.isArray(value)) {
    return value.join(", ");
  }
  if (typeof value === "string" || typeof value === "number") {
    return String(value);
  }
  if (value && typeof value === "object" && "value" in value && "unit" in value) {
    return `${value.value}${value.unit}`;
  }
  throw new Error(`Unsupported token value: ${JSON.stringify(value)}`);
}

function cssName(tokenPath) {
  const [layer, ...rest] = tokenPath;
  if (layer === "semantic") {
    return `--design-${rest.map(kebabCase).join("-")}`;
  }
  if (layer === "component") {
    return `--${rest.map(kebabCase).join("-")}`;
  }
  return `--${[layer, ...rest].map(kebabCase).join("-")}`;
}

function themeName(token) {
  const [, ...rest] = token.path;
  const withoutColor = rest[0] === "color" ? rest.slice(1) : rest;
  const namespace = token.type === "color" ? "color" : token.type === "fontFamily" ? "font" : null;
  return namespace ? `--${namespace}-${withoutColor.map(kebabCase).join("-")}` : null;
}

export function compileDesignSystem(documents, options = {}) {
  const merged = documents.reduce((result, document) => deepMerge(result, document), {});
  const tokens = flattenTokens(merged);
  const resolved = new Map();

  function resolve(tokenPath, stack = []) {
    if (resolved.has(tokenPath)) {
      return resolved.get(tokenPath);
    }
    if (stack.includes(tokenPath)) {
      throw new Error(`Circular token reference: ${[...stack, tokenPath].join(" -> ")}`);
    }
    const token = tokens.get(tokenPath);
    if (!token) {
      throw new Error(`Unknown token reference: ${tokenPath}`);
    }
    const alias = typeof token.value === "string" ? token.value.match(aliasPattern) : null;
    const value = alias ? resolve(alias[1], [...stack, tokenPath]) : formatValue(token.value);
    resolved.set(tokenPath, value);
    return value;
  }

  const sorted = [...tokens.entries()].sort(([a], [b]) => a.localeCompare(b));
  const rootLines = sorted.map(([tokenPath, token]) => `  ${cssName(token.path)}: ${resolve(tokenPath)};`);
  const themeLines = sorted
    .map(([, token]) => {
      const name = themeName(token);
      return name ? `  ${name}: var(${cssName(token.path)});` : null;
    })
    .filter(Boolean);

  const name = options.name ?? "Storefront";
  const primaryAction = resolved.get("semantic.color.action.primary.background") ?? "not configured";
  const surface = resolved.get("semantic.color.surface.canvas") ?? resolved.get("semantic.color.surface.raised") ?? "not configured";
  const content = resolved.get("semantic.color.content.primary") ?? "not configured";

  return {
    css: `/* Generated by scripts/design/generate-design.mjs. Do not edit. */\n:root {\n${rootLines.join("\n")}\n}\n\n@theme inline {\n${themeLines.join("\n")}\n}\n`,
    designMarkdown: `---\nversion: alpha\nname: ${name}\ndescription: Universal semantic commerce design system generated from DTCG tokens.\n---\n\n## Overview\n\nA restrained commerce foundation. Components consume semantic roles; store identity lives in approved token overrides.\n\n## Colors\n\n- Primary action: \`${primaryAction}\`\n- Canvas/raised surface: \`${surface}\`\n- Primary content: \`${content}\`\n\n## Components\n\nProduct cards use component aliases for background, content, radius, border, and action states.\n\n## Do's and Don'ts\n\n- Do use semantic or component tokens.\n- Do preserve visible focus, stock, price, and error states.\n- Don't introduce template color names or hard-coded visual values in components.\n`,
    manifest: {
      name,
      tokens: Object.fromEntries(
        sorted.map(([tokenPath, token]) => [
          tokenPath,
          { type: token.type, value: token.value, resolvedValue: resolve(tokenPath), cssVariable: cssName(token.path) },
        ])
      ),
    },
  };
}

async function runCli() {
  const appRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
  const inputPaths = [
    "design/tokens/reference.tokens.json",
    "design/tokens/semantic.tokens.json",
    "design/tokens/component.tokens.json",
    "design/themes/store.tokens.json",
  ];
  const documents = await Promise.all(
    inputPaths.map(async (relativePath) => JSON.parse(await readFile(path.join(appRoot, relativePath), "utf8")))
  );

  // Validate store-layer overrides against the editor registry.
  // Only paths registered in editor.registry.mjs may appear in store.tokens.json.
  const storeDoc = documents.at(-1);
  const storeTokens = flattenTokens(storeDoc);
  const registryErrors = [];
  for (const [tokenPath, token] of storeTokens) {
    // Skip metadata keys ($description etc)
    if (tokenPath.startsWith("$")) { continue; }
    const entry = getRegistryIndex().get(tokenPath);
    if (!entry) {
      registryErrors.push(`  unregistered path: ${tokenPath}`);
      continue;
    }
    const rawValue = String(token.value);
    if (!isAllowedEdit(tokenPath, rawValue)) {
      registryErrors.push(`  disallowed value for ${tokenPath}: ${rawValue}`);
    }
  }
  if (registryErrors.length > 0) {
    throw new Error(`store.tokens.json registry validation failed:\n${registryErrors.join("\n")}`);
  }

  const output = compileDesignSystem(documents, { name: "Vulpy Commerce" });

  // Skip DESIGN.md generation if a hand-written version exists (version >= "1.0")
  const designPath = path.join(appRoot, "DESIGN.md");
  let skipDesignMd = false;
  try {
    const existing = await readFile(designPath, "utf8");
    if (OLD_DESIGN_MD_VERSION_RE.test(existing)) {
      skipDesignMd = true;
    }
  } catch {
    // File doesn't exist — generate it
  }

  const artifacts = [
    [path.join(appRoot, "src/app/css/tokens.generated.css"), output.css],
    ...(skipDesignMd ? [] : [[designPath, output.designMarkdown]]),
    [path.join(appRoot, ".impeccable/design.json"), `${JSON.stringify(output.manifest, null, 2)}\n`],
  ];

  if (process.argv.includes("--check")) {
    const stale = [];
    for (const [artifactPath, expected] of artifacts) {
      let actual;
      try {
        actual = await readFile(artifactPath, "utf8");
      } catch {
        actual = null;
      }
      if (actual !== expected) {
        stale.push(path.relative(appRoot, artifactPath));
      }
    }
    if (stale.length > 0) {
      throw new Error(`Generated design artifacts are stale: ${stale.join(", ")}`);
    }
    return;
  }

  await mkdir(path.join(appRoot, ".impeccable"), { recursive: true });
  await Promise.all(artifacts.map(([artifactPath, content]) => writeFile(artifactPath, content)));
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  await runCli();
}
