/**
 * Contract test: the merged approval poll + cross-session banner injected
 * into static/messages.js by scripts/patch-webui-global-approval-banner.py
 * (issue #136 v2).
 *
 * The banner machinery is GENERATED by the patcher, so this test evaluates the
 * patcher's actual injected source (module NEW constant) in jsdom with stubbed
 * api/S/approval helpers. The single source of truth is the patcher script —
 * not a copy of the JS — so the test stays correct when the patcher drifts.
 *
 * Behaviors (issue #136 v2):
 *   - the banner renders inside #composerWrap .composer-flyout (not body)
 *   - dedicated styles are injected as one <style> tag
 *   - respond posts {session_id, choice, approval_id} to /api/approval/respond
 *     with an 8s timeout and no retries
 *   - in-flight guard: duplicate clicks drop, buttons disable while pending
 *   - stale-guard: a response for a superseded approval does not clear the
 *     banner entry now showing
 *   - the merged poll feeds BOTH the per-session card and the banner from one
 *     /api/approval/pending response
 *   - the merged poll is idempotent (one live timer, old one cleared)
 *   - the per-session showApprovalCard path is untouched by the banner
 */
import { execSync } from "node:child_process";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

const PATCHER_PATH = join(
  import.meta.dirname,
  "..",
  "scripts",
  "patch-webui-global-approval-banner.py",
);

// The exact JS the patcher injects into messages.js (OLD + banner machinery).
const INJECTED_JS: string = execSync(
  `python3 -c "import importlib.util as u; s=u.spec_from_file_location('banner_patcher', '${PATCHER_PATH}'); m=u.module_from_spec(s); s.loader.exec_module(m); print(m.NEW)"`,
  { encoding: "utf-8" },
);

// Expose the banner functions after evaluating the injected JS.  The getter
// re-reads the let-bound state so tests can assert current values.
const HARNESS = `
globalThis.__vulpyGlobalBannerTest = {
  showApprovalForSession,
  _showGlobalApprovalBanner,
  _hideGlobalApprovalBanner,
  dismissGlobalApprovalBanner,
  respondGlobalApproval,
  _startMergedApprovalPoll,
  _mergedApprovalPollTick,
  _globalApprovalViewedSid,
  _globalApprovalSetBusy,
  _updateApprovalIndicator,
  _sanitizeDenyReason,
  get _globalApprovalEntry() { return _globalApprovalEntry; },
  get _globalApprovalResponding() { return _globalApprovalResponding; },
  get _approvalIndicatorCount() { return _approvalIndicatorCount; },
};
`;

interface BannerTestApi {
  showApprovalForSession: (
    sid: string,
    pending: Record<string, unknown>,
    pendingCount: number,
  ) => void;
  _showGlobalApprovalBanner: (entry: Record<string, unknown>) => void;
  dismissGlobalApprovalBanner: () => void;
  respondGlobalApproval: (choice: string) => Promise<void>;
  _startMergedApprovalPoll: (sid: string) => void;
  _mergedApprovalPollTick: () => void;
  _globalApprovalViewedSid: () => string | null;
  _globalApprovalSetBusy: (busy: boolean) => void;
  _updateApprovalIndicator: (count?: number) => void;
  _sanitizeDenyReason: (raw: unknown) => string;
  _globalApprovalEntry: Record<string, unknown> | null;
  _globalApprovalResponding: Record<string, unknown> | null;
  _approvalIndicatorCount: number;
}

type MockFn = ReturnType<typeof vi.fn>;

const realSetInterval = globalThis.setInterval.bind(globalThis);
const realClearInterval = globalThis.clearInterval.bind(globalThis);

describe("global approval banner (patcher-injected messages.js, v2)", () => {
  let banner: BannerTestApi;
  let api: MockFn;
  let showApprovalCard: MockFn;
  let approvalPromptBelongsToActiveSession: MockFn;
  let isApprovalDismissed: MockFn;
  let markApprovalDismissed: MockFn;
  let clearApprovalPendingForSession: MockFn;
  let unmarkApprovalDismissed: MockFn;
  let hideApprovalCardIfOwner: MockFn;
  let showToast: MockFn;
  const pendingIntervals: ReturnType<typeof setInterval>[] = [];

  beforeEach(() => {
    api = vi.fn().mockResolvedValue({ ok: true });
    showApprovalCard = vi.fn();
    approvalPromptBelongsToActiveSession = vi.fn().mockReturnValue(false);
    isApprovalDismissed = vi.fn().mockReturnValue(false);
    markApprovalDismissed = vi.fn();
    clearApprovalPendingForSession = vi.fn();
    unmarkApprovalDismissed = vi.fn();
    hideApprovalCardIfOwner = vi.fn();
    showToast = vi.fn();

    // Globals the banner code resolves at call time.
    const g = globalThis as Record<string, unknown>;
    g.api = api;
    g.showApprovalCard = showApprovalCard;
    g._approvalPromptBelongsToActiveSession = approvalPromptBelongsToActiveSession;
    g._isApprovalDismissed = isApprovalDismissed;
    g._markApprovalDismissed = markApprovalDismissed;
    g._clearApprovalPendingForSession = clearApprovalPendingForSession;
    g._unmarkApprovalDismissed = unmarkApprovalDismissed;
    g._hideApprovalCardIfOwner = hideApprovalCardIfOwner;
    g._approvalPollingSessionMissingOrMismatched = () => false;
    g._approvalFallbackPollInFlight = false;
    g._approvalPollingSessionId = "viewed-session";
    g._approvalPendingBySession = new Map();
    g._syncApprovalTranscriptSpace = vi.fn();
    g._approvalMessagesNearBottom = () => false;
    g.scrollToBottom = vi.fn();
    g.showToast = showToast;
    g._promptActiveSessionId = () => null;
    g.S = { session: { session_id: "viewed-session" } };

    vi.spyOn(globalThis, "setInterval").mockImplementation((fn, ms) => {
      const id = realSetInterval(fn as () => void, ms);
      pendingIntervals.push(id);
      return id;
    });
    vi.spyOn(globalThis, "clearInterval").mockImplementation((id) => {
      realClearInterval(id);
    });

    document.body.innerHTML = "";

    // Evaluate fresh per test so the module-level let state never leaks.
    new Function(`${INJECTED_JS}\n${HARNESS}`)();
    banner = (globalThis as Record<string, unknown>)
      .__vulpyGlobalBannerTest as BannerTestApi;
  });

  afterEach(() => {
    for (const id of pendingIntervals) {
      clearInterval(id);
    }
    pendingIntervals.length = 0;
    (globalThis as Record<string, unknown>).__vulpyGlobalBannerTest = undefined;
    vi.restoreAllMocks();
  });

  it("renders a banner when a cross-session approval is pending", () => {
    banner._showGlobalApprovalBanner({
      _session_id: "child-session-1",
      session_id: "child-session-1",
      approval_id: "stamp-1",
      description: "run destructive command",
      command: "bash -c rm -rf /tmp/x",
    });

    const el = document.getElementById("globalApprovalBanner");
    expect(el).not.toBeNull();
    expect(el!.hidden).toBe(false);
    expect(el!.classList.contains("visible")).toBe(true);
    expect(el!.querySelector(".approval-desc")?.textContent).toContain(
      "run destructive command",
    );
    expect(el!.querySelector(".approval-cmd")?.textContent).toBe(
      "bash -c rm -rf /tmp/x",
    );
    expect(banner._globalApprovalEntry).toMatchObject({
      session_id: "child-session-1",
      approval_id: "stamp-1",
    });
  });

  it("places the banner inside the composer flyout, not document.body", () => {
    document.body.innerHTML =
      '<div id="composerWrap"><div class="composer-flyout"></div></div>';

    banner._showGlobalApprovalBanner({
      _session_id: "child-session-1b",
      approval_id: "stamp-1b",
    });

    const flyout = document.querySelector(".composer-flyout");
    expect(flyout?.querySelector("#globalApprovalBanner")).not.toBeNull();
    expect(document.body.querySelector(":scope > #globalApprovalBanner")).toBeNull();
  });

  it("injects dedicated banner styles once", () => {
    banner._showGlobalApprovalBanner({
      _session_id: "child-session-1c",
      approval_id: "stamp-1c",
    });
    banner._showGlobalApprovalBanner({
      _session_id: "child-session-1d",
      approval_id: "stamp-1d",
    });

    const styles = document.querySelectorAll("#vulpyGlobalApprovalStyles");
    expect(styles.length).toBe(1);
    expect(styles[0]!.textContent).toContain(".vulpy-global-approval-badge");
    expect(styles[0]!.textContent).toContain(
      "#approvalCard.visible ~ .vulpy-global-approval-banner",
    );
  });

  it("does NOT render for the viewed session (per-session card owns it)", () => {
    approvalPromptBelongsToActiveSession.mockReturnValue(true);
    banner._showGlobalApprovalBanner({
      session_id: "viewed-session",
      approval_id: "stamp-2",
    });

    const el = document.getElementById("globalApprovalBanner");
    expect(el === null || el.hidden).toBe(true);
    // The banner must not call the per-session card.
    expect(showApprovalCard).not.toHaveBeenCalled();
  });

  it("respond posts {session_id, choice, approval_id} with 8s timeout, no retries", async () => {
    banner._showGlobalApprovalBanner({
      _session_id: "child-session-2",
      approval_id: "stamp-3",
      description: "cmd",
      command: "ls -la",
    });
    await banner.respondGlobalApproval("once");

    expect(api).toHaveBeenCalledWith("/api/approval/respond", {
      method: "POST",
      timeoutMs: 8000,
      retries: 0,
      timeoutToast: false,
      body: JSON.stringify({
        session_id: "child-session-2",
        choice: "once",
        approval_id: "stamp-3",
      }),
    });
    expect(clearApprovalPendingForSession).toHaveBeenCalledWith("child-session-2");
    expect(banner._globalApprovalEntry).toBeNull();
  });

  it("shows a toast when the response is rejected", async () => {
    api.mockResolvedValue({ ok: false, error: "nope" });
    banner._showGlobalApprovalBanner({
      _session_id: "child-session-2b",
      approval_id: "stamp-3b",
    });
    await banner.respondGlobalApproval("deny");

    expect(showToast).toHaveBeenCalledWith("nope", 5000);
    expect(banner._globalApprovalEntry).not.toBeNull();
  });

  it("drops duplicate clicks while a respond is in flight and disables buttons", async () => {
    let resolveApi: (v: unknown) => void = () => {};
    api.mockImplementation(
      () => new Promise((res) => { resolveApi = res; }),
    );
    banner._showGlobalApprovalBanner({
      _session_id: "child-session-2c",
      approval_id: "stamp-3c",
    });

    const first = banner.respondGlobalApproval("once");
    const second = banner.respondGlobalApproval("once");
    await Promise.resolve();

    expect(api).toHaveBeenCalledTimes(1);
    expect(banner._globalApprovalResponding).toMatchObject({
      session_id: "child-session-2c",
      approval_id: "stamp-3c",
    });
    const buttons = document.querySelectorAll(
      "#globalApprovalBanner .approval-btns button",
    );
    for (const b of buttons) {
      expect((b as HTMLButtonElement).disabled).toBe(true);
    }

    resolveApi({ ok: true });
    await first;
    await second;
    expect(banner._globalApprovalEntry).toBeNull();
    expect(banner._globalApprovalResponding).toBeNull();
  });

  it("stale-guard: an answered approval that was superseded does not clear the new entry", async () => {
    let resolveApi: (v: unknown) => void = () => {};
    api.mockImplementation(
      () => new Promise((res) => { resolveApi = res; }),
    );
    banner._showGlobalApprovalBanner({
      _session_id: "child-session-2d",
      approval_id: "stamp-3d",
    });

    const pending = banner.respondGlobalApproval("once");
    await Promise.resolve();

    // The poll swaps in a newer approval before the respond resolves.
    banner._showGlobalApprovalBanner({
      _session_id: "child-session-2e",
      approval_id: "stamp-3e",
    });
    resolveApi({ ok: true });
    await pending;

    expect(banner._globalApprovalEntry).toMatchObject({
      session_id: "child-session-2e",
      approval_id: "stamp-3e",
    });
    expect(clearApprovalPendingForSession).not.toHaveBeenCalledWith(
      "child-session-2d",
    );
  });

  it("is dismissible without posting", () => {
    banner._showGlobalApprovalBanner({
      _session_id: "child-session-3",
      approval_id: "stamp-4",
    });
    banner.dismissGlobalApprovalBanner();

    expect(markApprovalDismissed).toHaveBeenCalledWith(
      "child-session-3",
      "stamp-4",
    );
    expect(clearApprovalPendingForSession).toHaveBeenCalledWith("child-session-3");
    expect(banner._globalApprovalEntry).toBeNull();
  });

  it("keeps the per-session showApprovalCard path untouched", () => {
    // The patcher output must not redefine the per-session card or the old
    // v1 poll machinery.
    expect(INJECTED_JS).not.toMatch(/function showApprovalCard\(/);
    expect(INJECTED_JS).not.toMatch(/_startGlobalApprovalPoll/);
    // The per-session helper still forwards to showApprovalCard.
    banner.showApprovalForSession("viewed-session", { approval_id: "stamp-5" }, 1);
    expect(showApprovalCard).toHaveBeenCalledWith(
      { approval_id: "stamp-5", _session_id: "viewed-session" },
      1,
    );
  });

  it("merged poll is idempotent (previous timer cleared, one live)", () => {
    api.mockResolvedValue({ approvals: [] });
    const setIntervalSpy = vi.mocked(globalThis.setInterval);
    const clearIntervalSpy = vi.mocked(globalThis.clearInterval);

    banner._startMergedApprovalPoll("viewed-session");
    const firstId = setIntervalSpy.mock.results[0]!.value;
    banner._startMergedApprovalPoll("viewed-session");

    expect(setIntervalSpy).toHaveBeenCalledTimes(2);
    expect(clearIntervalSpy).toHaveBeenCalledWith(firstId);
  });

  it("merged poll feeds the per-session card AND the banner from one response", async () => {
    api.mockResolvedValue({
      approvals: [
        { session_id: "viewed-session", approval_id: "a-viewed", description: "viewed cmd" },
        { session_id: "other-session", approval_id: "a-other", description: "other cmd" },
      ],
      pending_count: 2,
    });

    banner._mergedApprovalPollTick();
    await Promise.resolve();
    await Promise.resolve();

    // Viewed-session entry went to the per-session card.
    expect(showApprovalCard).toHaveBeenCalledWith(
      expect.objectContaining({ approval_id: "a-viewed", _session_id: "viewed-session" }),
      2,
    );
    // Other-session entry went to the banner.
    expect(banner._globalApprovalEntry).toMatchObject({
      session_id: "other-session",
      approval_id: "a-other",
    });
  });

  it("re-ticks immediately when the tab returns to the foreground", async () => {
    // Approval arrives while hidden; we start the poll then bring the tab back.
    api.mockResolvedValue({
      approvals: [{ session_id: "child-v", approval_id: "stamp-vis", description: "vis cmd" }],
      pending_count: 1,
    });

    banner._startMergedApprovalPoll("viewed-session");
    // Let the initial tick's promise chain (.then→.catch→.finally) settle so the
    // in-flight guard clears before we simulate the foreground return.
    for (let i = 0; i < 6 && (banner as unknown as { _approvalFallbackPollInFlight?: boolean })._approvalFallbackPollInFlight !== false; i++) {
      await Promise.resolve();
    }
    expect(api).toHaveBeenCalledTimes(1);

    // Simulate tab hidden → visible. jsdom fires visibilitychange on the added
    // listener; the handler must NOT re-tick while hidden.
    Object.defineProperty(document, "hidden", { value: true, configurable: true });
    document.dispatchEvent(new Event("visibilitychange"));
    expect(api).toHaveBeenCalledTimes(1);

    Object.defineProperty(document, "hidden", { value: false, configurable: true });
    document.dispatchEvent(new Event("visibilitychange"));
    await Promise.resolve();

    // Immediate re-tick on foreground return — no waiting for the next 1.5s tick.
    expect(api).toHaveBeenCalledTimes(2);
  });

  it("merged poll hides the banner when no cross-session approval remains", async () => {
    banner._showGlobalApprovalBanner({
      _session_id: "child-session-4",
      approval_id: "stamp-6",
    });
    api.mockResolvedValue({ approvals: [] });
    banner._mergedApprovalPollTick();

    await Promise.resolve();
    await Promise.resolve();

    expect(banner._globalApprovalEntry).toBeNull();
  });
});

describe("global approval hardening v3: indicator + origin + deny-reason", () => {
  let banner: BannerTestApi;
  let api: MockFn;
  let showApprovalCard: MockFn;
  let approvalPromptBelongsToActiveSession: MockFn;
  let isApprovalDismissed: MockFn;
  let clearApprovalPendingForSession: MockFn;
  let hideApprovalCardIfOwner: MockFn;
  let showToast: MockFn;
  const pendingIntervals: ReturnType<typeof setInterval>[] = [];

  beforeEach(() => {
    api = vi.fn().mockResolvedValue({ ok: true });
    showApprovalCard = vi.fn();
    approvalPromptBelongsToActiveSession = vi.fn().mockReturnValue(false);
    isApprovalDismissed = vi.fn().mockReturnValue(false);
    clearApprovalPendingForSession = vi.fn();
    hideApprovalCardIfOwner = vi.fn();
    showToast = vi.fn();

    const g = globalThis as Record<string, unknown>;
    g.api = api;
    g.showApprovalCard = showApprovalCard;
    g._approvalPromptBelongsToActiveSession = approvalPromptBelongsToActiveSession;
    g._isApprovalDismissed = isApprovalDismissed;
    g._markApprovalDismissed = vi.fn();
    g._clearApprovalPendingForSession = clearApprovalPendingForSession;
    g._unmarkApprovalDismissed = vi.fn();
    g._hideApprovalCardIfOwner = hideApprovalCardIfOwner;
    g._approvalPollingSessionMissingOrMismatched = () => false;
    g._approvalFallbackPollInFlight = false;
    g._approvalPollingSessionId = "viewed-session";
    g._approvalPendingBySession = new Map();
    g._syncApprovalTranscriptSpace = vi.fn();
    g._approvalMessagesNearBottom = () => false;
    g.scrollToBottom = vi.fn();
    g.showToast = showToast;
    g._promptActiveSessionId = () => null;
    g.S = { session: { session_id: "viewed-session" } };

    vi.spyOn(globalThis, "setInterval").mockImplementation((fn, ms) => {
      const id = realSetInterval(fn as () => void, ms);
      pendingIntervals.push(id);
      return id;
    });
    vi.spyOn(globalThis, "clearInterval").mockImplementation((id) => {
      realClearInterval(id);
    });

    document.body.innerHTML = "";
    new Function(`${INJECTED_JS}\n${HARNESS}`)();
    banner = (globalThis as Record<string, unknown>)
      .__vulpyGlobalBannerTest as BannerTestApi;
  });

  afterEach(() => {
    for (const id of pendingIntervals) {
      clearInterval(id);
    }
    pendingIntervals.length = 0;
    (globalThis as Record<string, unknown>).__vulpyGlobalBannerTest = undefined;
    vi.restoreAllMocks();
  });

  it("indicator: no pending → hidden, zero count", () => {
    banner._updateApprovalIndicator();
    const el = document.getElementById("vulpyApprovalIndicator");
    expect(el).not.toBeNull();
    expect(el!.hidden).toBe(true);
    expect(banner._approvalIndicatorCount).toBe(0);
  });

  it("indicator: shows total pending count and is not visibility/rAF-gated", () => {
    // Simulate a backgrounded/unfocused tab: document.visibilityState is
    // hidden and the poll is still ticking. The indicator must still render
    // from the merged poll tick (setInterval), not rAF/visibility gating.
    Object.defineProperty(document, "visibilityState", {
      value: "hidden",
      configurable: true,
    });
    Object.defineProperty(document, "hidden", {
      value: true,
      configurable: true,
    });
    api.mockResolvedValue({
      approvals: [
        { session_id: "child-1", approval_id: "c1", run_id: "run-1" },
        { session_id: "child-2", approval_id: "c2", run_id: "run-2" },
      ],
      pending_count: 2,
    });

    banner._mergedApprovalPollTick();
    return Promise.resolve()
      .then(() => Promise.resolve())
      .then(() => {
        const el = document.getElementById("vulpyApprovalIndicator");
        expect(el).not.toBeNull();
        expect(el!.hidden).toBe(false);
        expect(el!.textContent).toContain("2");
        expect(banner._approvalIndicatorCount).toBe(2);
        // Must not be inside a rAF/visibility-gated render path — the pill
        // exists and is visible while the document is hidden.
        expect(el!.classList.contains("visible")).toBe(true);
      });
  });

  it("indicator: hides when poll reports zero pending", async () => {
    banner._updateApprovalIndicator(3);
    api.mockResolvedValue({ approvals: [], pending_count: 0 });
    banner._mergedApprovalPollTick();
    await Promise.resolve();
    await Promise.resolve();

    const el = document.getElementById("vulpyApprovalIndicator");
    expect(el!.hidden).toBe(true);
    expect(banner._approvalIndicatorCount).toBe(0);
  });

  it("indicator: click focuses the composer (does not open a stray modal)", () => {
    banner._updateApprovalIndicator(1);
    const el = document.getElementById("vulpyApprovalIndicator")!;
    const focusSpy = vi.fn();
    // The indicator click must try to focus the composer / bring the card up.
    (globalThis as Record<string, unknown>).focusComposer =
      focusSpy;
    el.click();
    expect(focusSpy).toHaveBeenCalled();
  });

  it("origin: banner badge shows session + run id for cross-session", () => {
    banner._showGlobalApprovalBanner({
      _session_id: "child-run-1",
      session_id: "child-run-1",
      run_id: "run-abc",
      approval_id: "stamp-origin",
      description: "originated",
      command: "ls",
    });
    const el = document.getElementById("globalApprovalBanner")!;
    const badge = el.querySelector(".vulpy-global-approval-badge");
    expect(badge).not.toBeNull();
    expect(badge!.textContent).toContain("child-run-1");
    expect(badge!.textContent).toContain("run-abc");
  });

  it("deny: banner includes an optional reason input that is relayed in POST", async () => {
    banner._showGlobalApprovalBanner({
      _session_id: "child-deny",
      approval_id: "stamp-deny",
      description: "cmd",
    });
    const el = document.getElementById("globalApprovalBanner")!;
    const input = el.querySelector(".approval-reason-input") as HTMLInputElement;
    expect(input).not.toBeNull();
    // Reveal + type
    input.value = "this surgery is a no-go";
    input.dispatchEvent(new Event("input", { bubbles: true }));
    await banner.respondGlobalApproval("deny");

    const posted = JSON.parse((api.mock.calls[0]![1] as { body: string }).body);
    expect(posted).toMatchObject({
      session_id: "child-deny",
      choice: "deny",
      approval_id: "stamp-deny",
      reason: "this surgery is a no-go",
    });
  });

  it("deny: empty reason is omitted from the POST", async () => {
    banner._showGlobalApprovalBanner({
      _session_id: "child-deny-2",
      approval_id: "stamp-deny-2",
    });
    await banner.respondGlobalApproval("deny");
    const posted = JSON.parse((api.mock.calls[0]![1] as { body: string }).body);
    expect(posted).not.toHaveProperty("reason");
  });

  it("deny: reason is capped at 500 chars", async () => {
    banner._showGlobalApprovalBanner({
      _session_id: "child-deny-cap",
      approval_id: "stamp-deny-cap",
    });
    const el = document.getElementById("globalApprovalBanner")!;
    const input = el.querySelector(".approval-reason-input") as HTMLInputElement;
    input.value = "x".repeat(800);
    await banner.respondGlobalApproval("deny");
    const posted = JSON.parse((api.mock.calls[0]![1] as { body: string }).body);
    expect(posted.reason).toBe("x".repeat(500));
    expect(posted.reason!.length).toBeLessThanOrEqual(500);
  });

  it("deny: control chars and newlines are stripped from the reason", async () => {
    banner._showGlobalApprovalBanner({
      _session_id: "child-deny-ctl",
      approval_id: "stamp-deny-ctl",
    });
    const el = document.getElementById("globalApprovalBanner")!;
    const input = el.querySelector(".approval-reason-input") as HTMLInputElement;
    // NB: jsdom (and HTML `<input type=text>`) strips \r and \n when .value is
    // set, so to exercise the sanitizer's control-char class we use chars that
    // survive input.value (tab, NUL, SOH) plus a whitespace run to assert the
    // single-quoted-line collapse.
    input.value = "rm -rf /\tnow run:\0\u0001sudo  rm -rf  evil  payload   ";
    await banner.respondGlobalApproval("deny");
    const posted = JSON.parse((api.mock.calls[0]![1] as { body: string }).body);
    // biome-ignore lint/suspicious/noControlCharactersInRegex: intentional control-char assertion
    expect(posted.reason).not.toMatch(/[\u0000-\u001f\u007f]/);
    expect(posted.reason).not.toMatch(/\n/);
    // Control chars + whitespace runs collapsed to a single space-separated line.
    expect(posted.reason).toBe("rm -rf / now run: sudo rm -rf evil payload");
  });

  it("_sanitizeDenyReason: non-string / empty returns clean values", () => {
    expect(banner._sanitizeDenyReason("")).toBe("");
    expect(banner._sanitizeDenyReason(null)).toBe("");
    expect(banner._sanitizeDenyReason(undefined)).toBe("");
    expect(banner._sanitizeDenyReason("  spaced  out  ")).toBe("spaced out");
  });
});
