/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'blog-categories': BlogCategory;
    tags: Tag;
    posts: Post;
    pages: Page;
    productContent: ProductContent;
    categoryContent: CategoryContent;
    'contact-submissions': ContactSubmission;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'blog-categories': BlogCategoriesSelect<false> | BlogCategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    productContent: ProductContentSelect<false> | ProductContentSelect<true>;
    categoryContent: CategoryContentSelect<false> | CategoryContentSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    footer: Footer;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories".
 */
export interface BlogCategory {
  id: number;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage?: (number | null) | Media;
  categories?: (number | BlogCategory)[] | null;
  tags?: (number | Tag)[] | null;
  authorName?: string | null;
  publishedAt?: string | null;
  views?: number | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  blocks?:
    | (
        | {
            slides?:
              | {
                  eyebrow?: string | null;
                  title: string;
                  discountValue?: string | null;
                  body?: string | null;
                  ctaLabel?: string | null;
                  ctaUrl?: string | null;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            promos?:
              | {
                  title: string;
                  priceLabel?: string | null;
                  offerText?: string | null;
                  ctaLabel?: string | null;
                  link?: string | null;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            badges?:
              | {
                  title: string;
                  description?: string | null;
                  icon?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            eyebrow?: string | null;
            title: string;
            limit?: number | null;
            categoryHandles?:
              | {
                  handle?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'categoryGrid';
          }
        | {
            title: string;
            eyebrow?: string | null;
            subtitle?: string | null;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            variant?: ('new-arrivals' | 'best-sellers' | 'related') | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'productGrid';
          }
        | {
            banners?:
              | {
                  eyebrow: string;
                  title: string;
                  subtitle?: string | null;
                  ctaLabel?: string | null;
                  ctaUrl?: string | null;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'promoBanners';
          }
        | {
            eyebrow?: string | null;
            title: string;
            body?: string | null;
            productName?: string | null;
            deadline?: string | null;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            image?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'countdownPromo';
          }
        | {
            eyebrow?: string | null;
            title: string;
            items?:
              | {
                  quote: string;
                  authorName: string;
                  authorRole?: string | null;
                  avatar?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            title: string;
            subtitle?: string | null;
            placeholder?: string | null;
            bgImage?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsletter';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            contactName?: string | null;
            contactPhone?: string | null;
            contactEmail?: string | null;
            contactAddress?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactInfo';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactForm';
          }
        | {
            title: string;
            body?: string | null;
            theme?: ('blue' | 'teal' | 'dark') | null;
            image?: (number | null) | Media;
            links?:
              | {
                  label: string;
                  url: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            eyebrow?: string | null;
            title: string;
            body?: string | null;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            image?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'banner';
          }
        | {
            title: string;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            mediaType: 'image' | 'upload' | 'youtube' | 'vimeo';
            image?: (number | null) | Media;
            video?: (number | null) | Media;
            /**
             * YouTube or Vimeo link (e.g. https://www.youtube.com/watch?v=…).
             */
            videoUrl?: string | null;
            autoplay?: boolean | null;
            mediaPosition?: ('left' | 'right') | null;
            swapOnMobile?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaWithText';
          }
        | {
            size?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'spacer';
          }
      )[]
    | null;
  layout?: ('contact' | 'generic' | 'error' | 'mail-success') | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  heroImage?: (number | null) | Media;
  contactName?: string | null;
  contactPhone?: string | null;
  contactEmail?: string | null;
  contactAddress?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productContent".
 */
export interface ProductContent {
  id: number;
  medusaProductId: string;
  handle: string;
  title: string;
  /**
   * Public storefront URL for this page.
   */
  storefrontUrl?: string | null;
  /**
   * Link to the record in Medusa Admin.
   */
  medusaAdminUrl?: string | null;
  /**
   * Overrides the short description below the product title. When empty, the Medusa product description is used.
   */
  shortDescription?: string | null;
  /**
   * Overrides the full description in the Description tab. When empty, the Medusa product description is used.
   */
  longDescription?: string | null;
  blocks?:
    | (
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            eyebrow?: string | null;
            title: string;
            items?:
              | {
                  quote: string;
                  authorName: string;
                  authorRole?: string | null;
                  avatar?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            title?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            title: string;
            body?: string | null;
            theme?: ('blue' | 'teal' | 'dark') | null;
            image?: (number | null) | Media;
            links?:
              | {
                  label: string;
                  url: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            caption?: string | null;
            image: number | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'media';
          }
        | {
            title: string;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            mediaType: 'image' | 'upload' | 'youtube' | 'vimeo';
            image?: (number | null) | Media;
            video?: (number | null) | Media;
            /**
             * YouTube or Vimeo link (e.g. https://www.youtube.com/watch?v=…).
             */
            videoUrl?: string | null;
            autoplay?: boolean | null;
            mediaPosition?: ('left' | 'right') | null;
            swapOnMobile?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaWithText';
          }
        | {
            size?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'spacer';
          }
      )[]
    | null;
  lastSyncedAt?: string | null;
  lastSyncStatus?: ('success' | 'error') | null;
  lastSyncSource?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categoryContent".
 */
export interface CategoryContent {
  id: number;
  /**
   * Medusa categories sync from the backend. Pseudo categories (e.g. sale) live in code. Create selection pages manually with kind “Selection page”.
   */
  kind?: ('medusa' | 'pseudo' | 'selection') | null;
  medusaCategoryId?: string | null;
  handle: string;
  /**
   * Storefront path for pseudo categories and selection pages (e.g. /sale).
   */
  route?: string | null;
  /**
   * Initial catalog query params (e.g. sale_only=true&colors=red&attr_gender=womens).
   */
  filterQuery?: string | null;
  title: string;
  /**
   * Public storefront URL for this page.
   */
  storefrontUrl?: string | null;
  /**
   * Link to the record in Medusa Admin.
   */
  medusaAdminUrl?: string | null;
  /**
   * Overrides the category name shown as the page heading.
   */
  h1?: string | null;
  hideSubcategoryThumbs?: boolean | null;
  hideProductListing?: boolean | null;
  /**
   * Used on catalog pages, for example /sale.
   */
  showCategoryFilter?: boolean | null;
  blocksAboveSubcategories?:
    | (
        | {
            slides?:
              | {
                  eyebrow?: string | null;
                  title: string;
                  discountValue?: string | null;
                  body?: string | null;
                  ctaLabel?: string | null;
                  ctaUrl?: string | null;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            promos?:
              | {
                  title: string;
                  priceLabel?: string | null;
                  offerText?: string | null;
                  ctaLabel?: string | null;
                  link?: string | null;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            badges?:
              | {
                  title: string;
                  description?: string | null;
                  icon?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            eyebrow?: string | null;
            title: string;
            limit?: number | null;
            categoryHandles?:
              | {
                  handle?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'categoryGrid';
          }
        | {
            title: string;
            eyebrow?: string | null;
            subtitle?: string | null;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            variant?: ('new-arrivals' | 'best-sellers' | 'related') | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'productGrid';
          }
        | {
            banners?:
              | {
                  eyebrow: string;
                  title: string;
                  subtitle?: string | null;
                  ctaLabel?: string | null;
                  ctaUrl?: string | null;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'promoBanners';
          }
        | {
            eyebrow?: string | null;
            title: string;
            body?: string | null;
            productName?: string | null;
            deadline?: string | null;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            image?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'countdownPromo';
          }
        | {
            eyebrow?: string | null;
            title: string;
            items?:
              | {
                  quote: string;
                  authorName: string;
                  authorRole?: string | null;
                  avatar?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            title: string;
            subtitle?: string | null;
            placeholder?: string | null;
            bgImage?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsletter';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            contactName?: string | null;
            contactPhone?: string | null;
            contactEmail?: string | null;
            contactAddress?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactInfo';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactForm';
          }
        | {
            title: string;
            body?: string | null;
            theme?: ('blue' | 'teal' | 'dark') | null;
            image?: (number | null) | Media;
            links?:
              | {
                  label: string;
                  url: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            eyebrow?: string | null;
            title: string;
            body?: string | null;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            image?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'banner';
          }
        | {
            title: string;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            mediaType: 'image' | 'upload' | 'youtube' | 'vimeo';
            image?: (number | null) | Media;
            video?: (number | null) | Media;
            /**
             * YouTube or Vimeo link (e.g. https://www.youtube.com/watch?v=…).
             */
            videoUrl?: string | null;
            autoplay?: boolean | null;
            mediaPosition?: ('left' | 'right') | null;
            swapOnMobile?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaWithText';
          }
        | {
            size?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'spacer';
          }
      )[]
    | null;
  blocksBelowSubcategories?:
    | (
        | {
            slides?:
              | {
                  eyebrow?: string | null;
                  title: string;
                  discountValue?: string | null;
                  body?: string | null;
                  ctaLabel?: string | null;
                  ctaUrl?: string | null;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            promos?:
              | {
                  title: string;
                  priceLabel?: string | null;
                  offerText?: string | null;
                  ctaLabel?: string | null;
                  link?: string | null;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            badges?:
              | {
                  title: string;
                  description?: string | null;
                  icon?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            eyebrow?: string | null;
            title: string;
            limit?: number | null;
            categoryHandles?:
              | {
                  handle?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'categoryGrid';
          }
        | {
            title: string;
            eyebrow?: string | null;
            subtitle?: string | null;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            variant?: ('new-arrivals' | 'best-sellers' | 'related') | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'productGrid';
          }
        | {
            banners?:
              | {
                  eyebrow: string;
                  title: string;
                  subtitle?: string | null;
                  ctaLabel?: string | null;
                  ctaUrl?: string | null;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'promoBanners';
          }
        | {
            eyebrow?: string | null;
            title: string;
            body?: string | null;
            productName?: string | null;
            deadline?: string | null;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            image?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'countdownPromo';
          }
        | {
            eyebrow?: string | null;
            title: string;
            items?:
              | {
                  quote: string;
                  authorName: string;
                  authorRole?: string | null;
                  avatar?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            title: string;
            subtitle?: string | null;
            placeholder?: string | null;
            bgImage?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsletter';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            contactName?: string | null;
            contactPhone?: string | null;
            contactEmail?: string | null;
            contactAddress?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactInfo';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactForm';
          }
        | {
            title: string;
            body?: string | null;
            theme?: ('blue' | 'teal' | 'dark') | null;
            image?: (number | null) | Media;
            links?:
              | {
                  label: string;
                  url: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            eyebrow?: string | null;
            title: string;
            body?: string | null;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            image?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'banner';
          }
        | {
            title: string;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            mediaType: 'image' | 'upload' | 'youtube' | 'vimeo';
            image?: (number | null) | Media;
            video?: (number | null) | Media;
            /**
             * YouTube or Vimeo link (e.g. https://www.youtube.com/watch?v=…).
             */
            videoUrl?: string | null;
            autoplay?: boolean | null;
            mediaPosition?: ('left' | 'right') | null;
            swapOnMobile?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaWithText';
          }
        | {
            size?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'spacer';
          }
      )[]
    | null;
  blocksBelowListing?:
    | (
        | {
            slides?:
              | {
                  eyebrow?: string | null;
                  title: string;
                  discountValue?: string | null;
                  body?: string | null;
                  ctaLabel?: string | null;
                  ctaUrl?: string | null;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            promos?:
              | {
                  title: string;
                  priceLabel?: string | null;
                  offerText?: string | null;
                  ctaLabel?: string | null;
                  link?: string | null;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            badges?:
              | {
                  title: string;
                  description?: string | null;
                  icon?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            eyebrow?: string | null;
            title: string;
            limit?: number | null;
            categoryHandles?:
              | {
                  handle?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'categoryGrid';
          }
        | {
            title: string;
            eyebrow?: string | null;
            subtitle?: string | null;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            variant?: ('new-arrivals' | 'best-sellers' | 'related') | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'productGrid';
          }
        | {
            banners?:
              | {
                  eyebrow: string;
                  title: string;
                  subtitle?: string | null;
                  ctaLabel?: string | null;
                  ctaUrl?: string | null;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'promoBanners';
          }
        | {
            eyebrow?: string | null;
            title: string;
            body?: string | null;
            productName?: string | null;
            deadline?: string | null;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            image?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'countdownPromo';
          }
        | {
            eyebrow?: string | null;
            title: string;
            items?:
              | {
                  quote: string;
                  authorName: string;
                  authorRole?: string | null;
                  avatar?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            title: string;
            subtitle?: string | null;
            placeholder?: string | null;
            bgImage?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsletter';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            contactName?: string | null;
            contactPhone?: string | null;
            contactEmail?: string | null;
            contactAddress?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactInfo';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactForm';
          }
        | {
            title: string;
            body?: string | null;
            theme?: ('blue' | 'teal' | 'dark') | null;
            image?: (number | null) | Media;
            links?:
              | {
                  label: string;
                  url: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            eyebrow?: string | null;
            title: string;
            body?: string | null;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            image?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'banner';
          }
        | {
            title: string;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            mediaType: 'image' | 'upload' | 'youtube' | 'vimeo';
            image?: (number | null) | Media;
            video?: (number | null) | Media;
            /**
             * YouTube or Vimeo link (e.g. https://www.youtube.com/watch?v=…).
             */
            videoUrl?: string | null;
            autoplay?: boolean | null;
            mediaPosition?: ('left' | 'right') | null;
            swapOnMobile?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaWithText';
          }
        | {
            size?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'spacer';
          }
      )[]
    | null;
  lastSyncedAt?: string | null;
  lastSyncStatus?: ('success' | 'error') | null;
  lastSyncSource?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Messages from the contact form (read-only).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  subject?: string | null;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user: number | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  pages?: {
    /**
     * Allow clients to find pages.
     */
    find?: boolean | null;
    /**
     * Allow clients to create pages.
     */
    create?: boolean | null;
    /**
     * Allow clients to update pages.
     */
    update?: boolean | null;
  };
  productContent?: {
    /**
     * Allow clients to find productContent.
     */
    find?: boolean | null;
    /**
     * Allow clients to update productContent.
     */
    update?: boolean | null;
  };
  categoryContent?: {
    /**
     * Allow clients to find categoryContent.
     */
    find?: boolean | null;
    /**
     * Allow clients to update categoryContent.
     */
    update?: boolean | null;
  };
  media?: {
    /**
     * Allow clients to find media.
     */
    find?: boolean | null;
    /**
     * Allow clients to create media.
     */
    create?: boolean | null;
    /**
     * Allow clients to update media.
     */
    update?: boolean | null;
  };
  posts?: {
    /**
     * Allow clients to find posts.
     */
    find?: boolean | null;
    /**
     * Allow clients to update posts.
     */
    update?: boolean | null;
  };
  siteSettings?: {
    /**
     * Allow clients to find site-settings global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update site-settings global.
     */
    update?: boolean | null;
  };
  navigation?: {
    /**
     * Allow clients to find navigation global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update navigation global.
     */
    update?: boolean | null;
  };
  footer?: {
    /**
     * Allow clients to find footer global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update footer global.
     */
    update?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'blog-categories';
        value: number | BlogCategory;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'productContent';
        value: number | ProductContent;
      } | null)
    | ({
        relationTo: 'categoryContent';
        value: number | CategoryContent;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories_select".
 */
export interface BlogCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  categories?: T;
  tags?: T;
  authorName?: T;
  publishedAt?: T;
  views?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              slides?:
                | T
                | {
                    eyebrow?: T;
                    title?: T;
                    discountValue?: T;
                    body?: T;
                    ctaLabel?: T;
                    ctaUrl?: T;
                    image?: T;
                    id?: T;
                  };
              promos?:
                | T
                | {
                    title?: T;
                    priceLabel?: T;
                    offerText?: T;
                    ctaLabel?: T;
                    link?: T;
                    image?: T;
                    id?: T;
                  };
              badges?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        categoryGrid?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              limit?: T;
              categoryHandles?:
                | T
                | {
                    handle?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        productGrid?:
          | T
          | {
              title?: T;
              eyebrow?: T;
              subtitle?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              variant?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        promoBanners?:
          | T
          | {
              banners?:
                | T
                | {
                    eyebrow?: T;
                    title?: T;
                    subtitle?: T;
                    ctaLabel?: T;
                    ctaUrl?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        countdownPromo?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              body?: T;
              productName?: T;
              deadline?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              items?:
                | T
                | {
                    quote?: T;
                    authorName?: T;
                    authorRole?: T;
                    avatar?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        newsletter?:
          | T
          | {
              title?: T;
              subtitle?: T;
              placeholder?: T;
              bgImage?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        contactInfo?:
          | T
          | {
              contactName?: T;
              contactPhone?: T;
              contactEmail?: T;
              contactAddress?: T;
              id?: T;
              blockName?: T;
            };
        contactForm?:
          | T
          | {
              title?: T;
              subtitle?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              body?: T;
              theme?: T;
              image?: T;
              links?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        banner?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              body?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        mediaWithText?:
          | T
          | {
              title?: T;
              content?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              mediaType?: T;
              image?: T;
              video?: T;
              videoUrl?: T;
              autoplay?: T;
              mediaPosition?: T;
              swapOnMobile?: T;
              id?: T;
              blockName?: T;
            };
        spacer?:
          | T
          | {
              size?: T;
              id?: T;
              blockName?: T;
            };
      };
  layout?: T;
  content?: T;
  heroImage?: T;
  contactName?: T;
  contactPhone?: T;
  contactEmail?: T;
  contactAddress?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productContent_select".
 */
export interface ProductContentSelect<T extends boolean = true> {
  medusaProductId?: T;
  handle?: T;
  title?: T;
  storefrontUrl?: T;
  medusaAdminUrl?: T;
  shortDescription?: T;
  longDescription?: T;
  blocks?:
    | T
    | {
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              items?:
                | T
                | {
                    quote?: T;
                    authorName?: T;
                    authorRole?: T;
                    avatar?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              body?: T;
              theme?: T;
              image?: T;
              links?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        media?:
          | T
          | {
              caption?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        mediaWithText?:
          | T
          | {
              title?: T;
              content?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              mediaType?: T;
              image?: T;
              video?: T;
              videoUrl?: T;
              autoplay?: T;
              mediaPosition?: T;
              swapOnMobile?: T;
              id?: T;
              blockName?: T;
            };
        spacer?:
          | T
          | {
              size?: T;
              id?: T;
              blockName?: T;
            };
      };
  lastSyncedAt?: T;
  lastSyncStatus?: T;
  lastSyncSource?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categoryContent_select".
 */
export interface CategoryContentSelect<T extends boolean = true> {
  kind?: T;
  medusaCategoryId?: T;
  handle?: T;
  route?: T;
  filterQuery?: T;
  title?: T;
  storefrontUrl?: T;
  medusaAdminUrl?: T;
  h1?: T;
  hideSubcategoryThumbs?: T;
  hideProductListing?: T;
  showCategoryFilter?: T;
  blocksAboveSubcategories?:
    | T
    | {
        hero?:
          | T
          | {
              slides?:
                | T
                | {
                    eyebrow?: T;
                    title?: T;
                    discountValue?: T;
                    body?: T;
                    ctaLabel?: T;
                    ctaUrl?: T;
                    image?: T;
                    id?: T;
                  };
              promos?:
                | T
                | {
                    title?: T;
                    priceLabel?: T;
                    offerText?: T;
                    ctaLabel?: T;
                    link?: T;
                    image?: T;
                    id?: T;
                  };
              badges?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        categoryGrid?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              limit?: T;
              categoryHandles?:
                | T
                | {
                    handle?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        productGrid?:
          | T
          | {
              title?: T;
              eyebrow?: T;
              subtitle?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              variant?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        promoBanners?:
          | T
          | {
              banners?:
                | T
                | {
                    eyebrow?: T;
                    title?: T;
                    subtitle?: T;
                    ctaLabel?: T;
                    ctaUrl?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        countdownPromo?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              body?: T;
              productName?: T;
              deadline?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              items?:
                | T
                | {
                    quote?: T;
                    authorName?: T;
                    authorRole?: T;
                    avatar?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        newsletter?:
          | T
          | {
              title?: T;
              subtitle?: T;
              placeholder?: T;
              bgImage?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        contactInfo?:
          | T
          | {
              contactName?: T;
              contactPhone?: T;
              contactEmail?: T;
              contactAddress?: T;
              id?: T;
              blockName?: T;
            };
        contactForm?:
          | T
          | {
              title?: T;
              subtitle?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              body?: T;
              theme?: T;
              image?: T;
              links?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        banner?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              body?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        mediaWithText?:
          | T
          | {
              title?: T;
              content?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              mediaType?: T;
              image?: T;
              video?: T;
              videoUrl?: T;
              autoplay?: T;
              mediaPosition?: T;
              swapOnMobile?: T;
              id?: T;
              blockName?: T;
            };
        spacer?:
          | T
          | {
              size?: T;
              id?: T;
              blockName?: T;
            };
      };
  blocksBelowSubcategories?:
    | T
    | {
        hero?:
          | T
          | {
              slides?:
                | T
                | {
                    eyebrow?: T;
                    title?: T;
                    discountValue?: T;
                    body?: T;
                    ctaLabel?: T;
                    ctaUrl?: T;
                    image?: T;
                    id?: T;
                  };
              promos?:
                | T
                | {
                    title?: T;
                    priceLabel?: T;
                    offerText?: T;
                    ctaLabel?: T;
                    link?: T;
                    image?: T;
                    id?: T;
                  };
              badges?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        categoryGrid?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              limit?: T;
              categoryHandles?:
                | T
                | {
                    handle?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        productGrid?:
          | T
          | {
              title?: T;
              eyebrow?: T;
              subtitle?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              variant?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        promoBanners?:
          | T
          | {
              banners?:
                | T
                | {
                    eyebrow?: T;
                    title?: T;
                    subtitle?: T;
                    ctaLabel?: T;
                    ctaUrl?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        countdownPromo?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              body?: T;
              productName?: T;
              deadline?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              items?:
                | T
                | {
                    quote?: T;
                    authorName?: T;
                    authorRole?: T;
                    avatar?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        newsletter?:
          | T
          | {
              title?: T;
              subtitle?: T;
              placeholder?: T;
              bgImage?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        contactInfo?:
          | T
          | {
              contactName?: T;
              contactPhone?: T;
              contactEmail?: T;
              contactAddress?: T;
              id?: T;
              blockName?: T;
            };
        contactForm?:
          | T
          | {
              title?: T;
              subtitle?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              body?: T;
              theme?: T;
              image?: T;
              links?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        banner?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              body?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        mediaWithText?:
          | T
          | {
              title?: T;
              content?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              mediaType?: T;
              image?: T;
              video?: T;
              videoUrl?: T;
              autoplay?: T;
              mediaPosition?: T;
              swapOnMobile?: T;
              id?: T;
              blockName?: T;
            };
        spacer?:
          | T
          | {
              size?: T;
              id?: T;
              blockName?: T;
            };
      };
  blocksBelowListing?:
    | T
    | {
        hero?:
          | T
          | {
              slides?:
                | T
                | {
                    eyebrow?: T;
                    title?: T;
                    discountValue?: T;
                    body?: T;
                    ctaLabel?: T;
                    ctaUrl?: T;
                    image?: T;
                    id?: T;
                  };
              promos?:
                | T
                | {
                    title?: T;
                    priceLabel?: T;
                    offerText?: T;
                    ctaLabel?: T;
                    link?: T;
                    image?: T;
                    id?: T;
                  };
              badges?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        categoryGrid?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              limit?: T;
              categoryHandles?:
                | T
                | {
                    handle?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        productGrid?:
          | T
          | {
              title?: T;
              eyebrow?: T;
              subtitle?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              variant?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        promoBanners?:
          | T
          | {
              banners?:
                | T
                | {
                    eyebrow?: T;
                    title?: T;
                    subtitle?: T;
                    ctaLabel?: T;
                    ctaUrl?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        countdownPromo?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              body?: T;
              productName?: T;
              deadline?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              items?:
                | T
                | {
                    quote?: T;
                    authorName?: T;
                    authorRole?: T;
                    avatar?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        newsletter?:
          | T
          | {
              title?: T;
              subtitle?: T;
              placeholder?: T;
              bgImage?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        contactInfo?:
          | T
          | {
              contactName?: T;
              contactPhone?: T;
              contactEmail?: T;
              contactAddress?: T;
              id?: T;
              blockName?: T;
            };
        contactForm?:
          | T
          | {
              title?: T;
              subtitle?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              body?: T;
              theme?: T;
              image?: T;
              links?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        banner?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              body?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        mediaWithText?:
          | T
          | {
              title?: T;
              content?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              mediaType?: T;
              image?: T;
              video?: T;
              videoUrl?: T;
              autoplay?: T;
              mediaPosition?: T;
              swapOnMobile?: T;
              id?: T;
              blockName?: T;
            };
        spacer?:
          | T
          | {
              size?: T;
              id?: T;
              blockName?: T;
            };
      };
  lastSyncedAt?: T;
  lastSyncStatus?: T;
  lastSyncSource?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  subject?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  pages?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  productContent?:
    | T
    | {
        find?: T;
        update?: T;
      };
  categoryContent?:
    | T
    | {
        find?: T;
        update?: T;
      };
  media?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  posts?:
    | T
    | {
        find?: T;
        update?: T;
      };
  siteSettings?:
    | T
    | {
        find?: T;
        update?: T;
      };
  navigation?:
    | T
    | {
        find?: T;
        update?: T;
      };
  footer?:
    | T
    | {
        find?: T;
        update?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  topBarText?: string | null;
  topBarLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  logo?: (number | null) | Media;
  checkoutLogo?: (number | null) | Media;
  supportPhone?: string | null;
  searchPlaceholder?: string | null;
  hideCart?: boolean | null;
  medusaCategoriesInNavigation?: ('before' | 'after' | 'hide') | null;
  contactInfo?: {
    address?: string | null;
    phone?: string | null;
    email?: string | null;
    contactName?: string | null;
  };
  socialLinks?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  defaultSeo?: {
    title?: string | null;
    description?: string | null;
  };
  utilityPageSeo?:
    | {
        route: string;
        title: string;
        description?: string | null;
        heading?: string | null;
        subheading?: string | null;
        id?: string | null;
      }[]
    | null;
  shopLabels?: {
    breadcrumb?: string | null;
    sortOptions?:
      | {
          value: 'latest' | 'oldest' | 'bestsellers' | 'price-asc' | 'price-desc' | 'name-asc' | 'name-desc';
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  authLabels?: {
    signInTitle?: string | null;
    signInSubtitle?: string | null;
    signUpTitle?: string | null;
    signUpSubtitle?: string | null;
  };
  /**
   * Payment method icons in the site footer and on product pages.
   */
  paymentMethods?:
    | {
        icon: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Shop-wide shipping and return details for Product Offer JSON-LD on PDPs (Google Merchant listings). Leave blank to omit those fields — do not invent policy data.
   */
  merchantListing?: {
    returnDays?: number | null;
    returnFees?: string | null;
    returnMethod?: string | null;
    returnCountry?: string | null;
    shippingRate?: number | null;
    shippingCurrency?: string | null;
    deliveryTimeMinDays?: number | null;
    deliveryTimeMaxDays?: number | null;
    shippingDestinationCountry?: string | null;
  };
  /**
   * Physical storefront for Google Maps / local SEO. Leave disabled if online-only. Emitted only on the homepage when enabled and address is complete.
   */
  showroom?: {
    enabled?: boolean | null;
    /**
     * Defaults to site name when empty
     */
    name?: string | null;
    type?: ('Store' | 'SportingGoodsStore') | null;
    streetAddress?: string | null;
    addressLocality?: string | null;
    addressRegion?: string | null;
    postalCode?: string | null;
    addressCountry?: string | null;
    telephone?: string | null;
    latitude?: number | null;
    longitude?: number | null;
    openingHours?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  items?:
    | {
        title: string;
        path: string;
        newTab?: boolean | null;
        submenu?:
          | {
              title: string;
              path: string;
              newTab?: boolean | null;
              /**
               * Hide this submenu link on desktop (e.g. “All …” parent link shown only on mobile).
               */
              mobileOnly?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Shown on every page directly above the site footer.
   */
  preFooterBlocks?:
    | (
        | {
            title: string;
            subtitle?: string | null;
            placeholder?: string | null;
            bgImage?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsletter';
          }
        | {
            title: string;
            body?: string | null;
            theme?: ('blue' | 'teal' | 'dark') | null;
            image?: (number | null) | Media;
            links?:
              | {
                  label: string;
                  url: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            size?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'spacer';
          }
      )[]
    | null;
  helpTitle?: string | null;
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              url: string;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        label: string;
        url: string;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  topBarText?: T;
  topBarLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  logo?: T;
  checkoutLogo?: T;
  supportPhone?: T;
  searchPlaceholder?: T;
  hideCart?: T;
  medusaCategoriesInNavigation?: T;
  contactInfo?:
    | T
    | {
        address?: T;
        phone?: T;
        email?: T;
        contactName?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  copyright?: T;
  defaultSeo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  utilityPageSeo?:
    | T
    | {
        route?: T;
        title?: T;
        description?: T;
        heading?: T;
        subheading?: T;
        id?: T;
      };
  shopLabels?:
    | T
    | {
        breadcrumb?: T;
        sortOptions?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  authLabels?:
    | T
    | {
        signInTitle?: T;
        signInSubtitle?: T;
        signUpTitle?: T;
        signUpSubtitle?: T;
      };
  paymentMethods?:
    | T
    | {
        icon?: T;
        id?: T;
      };
  merchantListing?:
    | T
    | {
        returnDays?: T;
        returnFees?: T;
        returnMethod?: T;
        returnCountry?: T;
        shippingRate?: T;
        shippingCurrency?: T;
        deliveryTimeMinDays?: T;
        deliveryTimeMaxDays?: T;
        shippingDestinationCountry?: T;
      };
  showroom?:
    | T
    | {
        enabled?: T;
        name?: T;
        type?: T;
        streetAddress?: T;
        addressLocality?: T;
        addressRegion?: T;
        postalCode?: T;
        addressCountry?: T;
        telephone?: T;
        latitude?: T;
        longitude?: T;
        openingHours?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        title?: T;
        path?: T;
        newTab?: T;
        submenu?:
          | T
          | {
              title?: T;
              path?: T;
              newTab?: T;
              mobileOnly?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  preFooterBlocks?:
    | T
    | {
        newsletter?:
          | T
          | {
              title?: T;
              subtitle?: T;
              placeholder?: T;
              bgImage?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              body?: T;
              theme?: T;
              image?: T;
              links?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        spacer?:
          | T
          | {
              size?: T;
              id?: T;
              blockName?: T;
            };
      };
  helpTitle?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              newTab?: T;
              id?: T;
            };
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        url?: T;
        newTab?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}